### ISSUE TITLE
windows installation - Where to put the ffmpeg files?

### ISSUE THREAD

**Issue by swirtgen** [navidrome/website#100]
search the site up and down, read about that I need ffmpeg - but no word about where to put in.
Navidrome shows up "level=warning msg="unable to find ffmpeg. Transcoding will fail if used" error="exec: \"ffmpeg\": executeable file not found in &PATH"

so first, which is the "PATH" ?
what to write down in Navidrome.toml ?

i create an folder inside the folder Navidrome with ffmpeg inside of it, but how to tell Navidrome to look inside that folder? (btw. folder called ffmpeg)
second try was to copy ffmpeg.exe directly inside the navidrome folder - no luck at all

So please update your Site with an example where to put ffmpeg and what to type in the config file

thank you :-)

**Comment by deluan** [comment]
Latest version (0.49.3) has a config option to set the full path of the `ffmpeg` executable, `FFmpegPath`. Just set it and Navidrome will be able to find `ffmpeg`

---
Using PATH: 

> so first, which is the "PATH" ?

This is the Windows system `PATH` environment variable. Here are [some tips](https://www.google.com/search?q=how+to+change+path+in+windows&rlz=1C5CHFA_enCA923CA923&oq=how+to+change+PATH+in+windows&aqs=chrome.0.0i512l6j0i22i30l4.4631j0j1&sourceid=chrome&ie=UTF-8) on how to change it.

Example: If you put `ffmpeg.exe` in `C:\Users\JohnDoe\Navidrome\ffmpeg\ffmpeg.exe ` you can add `C:\Users\JohnDoe\Navidrome\ffmpeg` to PATH, and Navidrome will be able to find it.
