### ISSUE TITLE
Needs Go and Node.js for source to be build on macOS

### ISSUE THREAD

**Issue by jjaarddev** [navidrome/website#112]
During building from source, after `brew install taglib` and `make setup` commands, I encountered a few small errors like:

```
/bin/sh: line 0: hash: go: not found
ERROR: GO environment not setup properly!
make: *** [check_go_env] Error 1
```

and

```
/bin/sh: line 0: hash: go: not found
ERROR: Node environment not setup properly!
make: *** [check_go_env] Error 1
```

so it needs **Go** (`brew install go`) and **nodejs** (`brew install nodejs`) to be able to build from source on macOS (Ventura at least), so I think it is worth to mention in documentation.

**Comment by jjaarddev** [comment]
just mentioning commands if some person not so experienced would encounter these errors so will know what to install via brew

**Comment by deluan** [comment]
The documentation already says you need Go and Node (before even talking about TagLib):

> First, you will need to install [Go 1.18](https://golang.org/doc/install) and [Node 16](http://nodejs.org/). The setup is very strict, and the steps below only work with these versions (enforced in the Makefile). Make sure to add $GOPATH/bin to your PATH as described in the [official Go site](https://golang.org/doc/gopath_code.html#GOPATH)

>You’ll also need to install the [TagLib](http://taglib.org/) library:

If this is not clear enough, feel free to submit a PR suggesting a different wording.
