### ISSUE TITLE
xxx

### ISSUE THREAD

**Issue by tommurphy78** [navidrome/website#116]
make it less complicated to install this. i bet if i spent 3 hours following these instructions to the letter, it still wouldn't work

**Comment by deluan** [comment]
Thank you for sharing your feedback. We understand that installing Navidrome can be challenging, and we are working to improve our installation process. If you are experiencing any issues or have specific questions, we would be happy to help. Please feel free to post your questions on Reddit or our Discord community channels. We also have a [CODE OF CONDUCT](https://github.com/navidrome/navidrome/blob/master/CODE_OF_CONDUCT.md) that outlines our expectations for respectful communication within the community. Thank you for your understanding.

**Comment by tommurphy78** [comment]
Hi there. I would like to report that I was able to get navidrome working in docker on my raspberrypi 4 and it is awesome! I am learning a lot about computers by installing this kind of music server software and I am very grateful that you are providing an alternative to the likes of Spotify and Apple Music. Thanks again and best wishes.
