### ISSUE TITLE
add nixos to community packages

### ISSUE THREAD

**Issue by quantenzitrone** [navidrome/website#152]
NixOS packages navidrome and provides a module to enable navidrome as a systemd service.
Link to the documentation is https://search.nixos.org/options?channel=unstable&query=services.navidrome
Navidrome is by default configured to run in a tight systemd sandbox and only listen to localhost, so the user can easily set up a reverse proxy.
See the modules code https://github.com/NixOS/nixpkgs/blob/79a13f1437e149dc7be2d1290c74d378dad60814/nixos/modules/services/audio/navidrome.nix for more details

**Comment by deluan** [comment]
Thanks for the suggestion, but NixOS packages are already show in the Repology list:

![Screenshot 2024-02-03 at 11 33 42 AM](https://github.com/navidrome/website/assets/331353/4adab748-1ce3-4b2c-acbf-de0a87d320d3)

**Comment by quantenzitrone** [comment]
I'm not sure how I missed that 3 days ago, and I feel quite dumb right now.
