### ISSUE TITLE
Document Jukebox.AdminOnly

### ISSUE THREAD

**Issue by quite** [navidrome/website#161]
Apparently, a new Jukebox.AdminOnly config bool was recently added, and it defaults to true. This needs to be documented on `/docs/usage/jukebox/` and `/docs/usage/configuration-options/`. So people are not left lost as to why jukebox doesn't work.

(perhaps if the website src lived in the same repo as the code, the keeping up to date of docs could be more smoother)

**Comment by deluan** [comment]
Ops, my bad, forgot to even mention it in the release notes. Fixed now.

> (perhaps if the website src lived in the same repo as the code, the keeping up to date of docs could be more smoother)

The website is in a different repository to make it simpler to get contributions: there are links in the site itself that open's a GitHub page with direct access to edit and create a PR.

Anyway, thanks for the suggestion.
