### ISSUE TITLE
Please include a section that explains how to use the Subsonic API

### ISSUE THREAD

**Issue by Igeljaeger** [navidrome/website#20]
The docs of similar software like Funkwhale make it quite easy. Your docs claim it should be available, yet there's no indication as to how or where to find the data for that. Edit: it seems to work with user-login data. Quite different from funkwhale, so maybe that's why I was confused.
https://docs.funkwhale.audio/users/apps.html

**Comment by deluan** [comment]
Glad you figured it out. Yeah, Navidrome's approach to the Subsonic API is more straightforward, more similar to Subsonic it self.
