### ISSUE TITLE
Add songs or albums within the interface

### ISSUE THREAD

**Issue by MrMorals** [navidrome/website#22]
So first of all, thanks for creating this amazing application!

Since Navidrome uses music that you already have, I was expecting that (admin) users could upload new songs when logged into the Navidrome panel. That would make it usable for me as me and my friends would share an instance and create a useful substantial music library fast.
I could not find information on this were I was expecting it in the demo. Also not though: https://www.navidrome.org/docs/getting-started/

Is this a feature that is in Navidrome? Would be well worth considering I think :smile:

**Comment by deluan** [comment]
Sorry for the delay. Navidrome does not support file upload, and will not support it any time soon, see: https://github.com/deluan/navidrome/issues/311

A simple solution is to pair Navidrome with FileBrowser, ex: https://github.com/geekedtv/Docker-Music-Stack
