### ISSUE TITLE
documentation : no import or add song instructions or links

### ISSUE THREAD

**Issue by timconsidine** [navidrome/website#24]
Just did a fresh install of Navidrome : looks great
But there are no buttons or links to import or add songs.
The links visible in the demo system flash on screen and then disappear with a "no content" message.
The documentation  does not say how to add a sing/album

**Comment by deluan** [comment]
Hey @timconsidine , thanks for giving Navidrome a try.

Currently the way to add your library to Navidrome is to point the `MusicFolder` configuration option to the folder you music library is located. Take a look at https://www.navidrome.org/docs/usage/configuration-options/

This will change when we introduce the [Multi-library](https://github.com/navidrome/navidrome/issues/192) support, there will be a way to add/remove new paths using the UI
