### ISSUE TITLE
Updating Doc's for Running navidrome on WINDOWS in Devlopement Enviroment

### ISSUE THREAD

**Issue by pritamp17** [navidrome/website#30]
There is no information present on how to run Navidrome on windows in Development env, I would like to add it.
I will add documentation on how to run Navidrome on windows using Windows Subsystem for Linux (WSL) + VsCode.
can I go ahead  @deluan  ??

**Comment by deluan** [comment]
Yes, please! Thanks for offering help!

**Comment by deluan** [comment]
Thanks for the PR, I edited it and did a full rewrite of that page, using your instructions
