### ISSUE TITLE
No ability to set user in Docker

### ISSUE THREAD

**Issue by DustbinK** [navidrome/website#44]
Container does not have a documented way to set the user ID/group ID via environmental variable or it's not documented

**Comment by deluan** [comment]
Hey @DustbinK, thanks for trying Navidrome!

There is an open issue for this in https://github.com/navidrome/navidrome/issues/531#issuecomment-699666366:
>We've discussed the possibility to enable this functionality (setting UID/GID with env vars) in the past, but decided against it because:
> - This is a responsibility of Docker itself (or the container platform used), not the app
> - I plan to eventually rewrite the docker images to be based on LinuxServer, and this is a given in their images.
>
>I'll keep this open, and will use this to track the LinuxServer "migration".

Currently the way to change UID/GID is to use Docker's `--user` flag (or `user` key in `docker-compose.yml`): https://www.navidrome.org/docs/installation/docker/#customization

Will close this as it is already being tracked in the aforementioned issue.

**Comment by DustbinK** [comment]
The platform I use does not let me set the user without using an environment variable. I do not use Docker through the command line or through compose. So the solution is to wait until you standardize on the same settings LinuxServer uses? I use a lot of their images without issue but it is unfortunate that it can't be implemented until then.

**Comment by deluan** [comment]
> So the solution is to wait until you standardize on the same settings LinuxServer uses?

Yeah, unfortunately you'll have to wait.... And it may take a while as I'm focused on adding new features and mentoring [GSoC](https://www.navidrome.org/docs/gsoc/). Unless someone steps in and creates an image from LinuxServer base images.
