### ISSUE TITLE
Update ARM version resource?

### ISSUE THREAD

**Issue by RyanTG** [navidrome/website#51]
**Background:**

In my recent experience, the [ARM table](https://www.riscosopen.org/wiki/documentation/show/ARMv7%20compatibility%20primer#introduction) that is linked to on the [Installation page](
https://www.navidrome.org/docs/installation/) was not accurate. I have a raspberry pi 3, which according to that site should use ARMv8. So I installed the v8 build (which doesn't actually say "v8" on it, which was a little confusing), and the service failed to start. After looking at `journalctl` I saw:

````
pi@raspberrypi:~ $ journalctl
-- Logs begin at Thu 2016-11-03 10:16:44 PDT, end at Thu 2021-07-01 15:10:02 PDT. --
Nov 03 10:16:44 raspberrypi kernel: Booting Linux on physical CPU 0x0
Nov 03 10:16:44 raspberrypi kernel: Linux version 4.19.66-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG cro
Nov 03 10:16:44 raspberrypi kernel: CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
````
Showing that I have ARMv7 on my raspberry 3. After looking into it, it looks like both Raspberry 3s and 4s can use ARMv7 in some cases. 

**Suggestion:**

So this issue is to see whether you think the website should offer a different method of checking the ARM version. Instead of a website, users should actually look at their system. One method is to run `cat /proc/cpuinfo`. Anyone know of another good method?

The line in question: https://github.com/navidrome/website/blame/master/content/en/docs/Installation/_index.md#L22

**Comment by deluan** [comment]
Sorry for the delay and thanks for the suggestion. A PR with some fool-proof instructions on how to know for sure the ARM version would be great!

**Comment by RyanTG** [comment]
https://github.com/navidrome/website/pull/60

Nothing fancy.

**Comment by deluan** [comment]
#60 was merged. Closing this now.
