### ISSUE TITLE
Reuse in other communities - SSO login

### ISSUE THREAD

**Issue by Thiagobhmg** [navidrome/website#56]
It would be interesting to implement SSO so that you can join this project on existing platforms with users already registered, so that the user does not need to make a new registration to use this platform.

**Comment by deluan** [comment]
Hey, sorry for the delay. We need the user and password created in Navidrome's DB, as this is a requirement for the Subsonic API. There are some [improvements proposed](https://github.com/navidrome/navidrome/issues/1189) to the current solution (using http-header authentication), but currently it is not possible to remove the user/password completely from Navidrome's DB.

Please subscribe to the ticket above for updates/discussions. I'll close this as this repository is just for the website, not the Navidrome server.
