### ISSUE TITLE
Search is a little broken

### ISSUE THREAD

**Issue by HardikRa** [navidrome/website#57]
The search appears to be showing code instead of (images?) that's from what I can read at least. 
![image](https://user-images.githubusercontent.com/56108057/128255867-45002b02-6649-4d4c-8dd4-0aff7edd27fe.png)

**Comment by deluan** [comment]
Sorry for the delay.

I couldn't reproduce this error... Can you give more details? On which page this error happened? What search term you used? Was it in mobile or desktop view?

**Comment by HardikRa** [comment]
I searched for 'host' on the home page

**Comment by AtharvaParkale** [comment]
> I searched for 'host' on the home page

Can i work on this issue

**Comment by AtharvaParkale** [comment]
> I searched for 'host' on the home page

I understood what you are saying

**Comment by deluan** [comment]
> > I searched for 'host' on the home page
> 
> Can i work on this issue

Sure.

**Comment by GeneralChauhan** [comment]
@AtharvaParkale  are you working on this? 
I would love to get started with this!

**Comment by deluan** [comment]
This has been fixed a while ago:
<img width="560" alt="Screenshot 2023-04-09 at 2 04 46 PM" src="https://user-images.githubusercontent.com/331353/230789099-8ed82f25-5cea-4367-9905-fd76d65503c3.png">

**Comment by GeneralChauhan** [comment]
oh, alright!
