### ISSUE TITLE
redesign error 404 page

### ISSUE THREAD

**Issue by khareyash05** [navidrome/website#67]
The current design of error 404 page looks dull . I would like to design a better one
![image](https://user-images.githubusercontent.com/60147732/141977160-57c5b112-2636-4645-807d-179a9ee63631.png)

**Comment by deluan** [comment]
Cool, feel free to send a PR. It would be great if the 404 page had some links to the important pages in the doc:


- [Overview](https://www.navidrome.org/docs/overview/)
- [Installation](https://www.navidrome.org/docs/installation/)
  - [Docker](https://www.navidrome.org/docs/installation/docker/)
  - [Binaries](https://www.navidrome.org/docs/installation/pre-built-binaries/)
  - [Build from source](https://www.navidrome.org/docs/installation/build-from-source/)
- [Development](https://www.navidrome.org/docs/developers/)
- [Subsonic API Compatibility](https://www.navidrome.org/docs/developers/subsonic-api/)

**Comment by khareyash05** [comment]
@deluan I am finding this error while typing hugo server kindly help
![image](https://user-images.githubusercontent.com/60147732/142574628-346ad997-f1e5-49af-b9ba-08e6031f0240.png)

**Comment by deluan** [comment]
Sorry, don't know what could be... Maybe an incompatible version? I'm using the following version:
> Hugo Static Site Generator v0.76.4/extended darwin/amd64 BuildDate: unknown

Or maybe you didn't checkout the submodules? Did you follow the instructions in the README?

```
git clone --recurse-submodules https://github.com/navidrome/website.git
cd website
npm install
```

**Comment by khareyash05** [comment]
I didnt checkout the submodules . My bad!

**Comment by khareyash05** [comment]
@deluan One more error I am facing kindly help. I am not able to reach the  error 404 page (404 page not found)

**Comment by deluan** [comment]
AFAIK Hugo does not render the 404 page locally. Try creating a PR in this repo, it will be deployed to Netlify and you can check the result by clicking here:
<img width="966" alt="Screen Shot 2021-11-20 at 12 41 41 PM" src="https://user-images.githubusercontent.com/331353/142736088-6b14ddc9-b48b-4df9-b5f6-cc85a386641f.png">

**Comment by khareyash05** [comment]
@deluan Everything works well except CSS of the website isnt runnning. I thought of converting it to SCSS but I think SCSS doesnt work on HTML pages.

**Comment by khareyash05** [comment]
@deluan Created a PR have a look!
