### ISSUE TITLE
ND_ENABLE_EXTERNAL_SERVICES is actually ND_ENABLEEXTERNALSERVICES

### ISSUE THREAD

**Issue by flako-dd** [navidrome/website#72]
Hi!

Minor Doc Issue:
```ND_ENABLE_EXTERNAL_SERVICES```
is actually:
```ND_ENABLEEXTERNALSERVICES```

since it gets autogenerated in [configuration](https://github.com/navidrome/navidrome/blob/master/conf/configuration.go). See [Specific Doc location](https://github.com/navidrome/website/blob/master/content/en/docs/Usage/configuration-options.md?plain=1#L95).

Regards.

**Comment by deluan** [comment]
Hey, good catch! Thanks!
