### ISSUE TITLE
Add hamburger menu for mobile view of the website

### ISSUE THREAD

**Issue by Daggerhub** [navidrome/website#75]
![WhatsApp Image 2022-01-24 at 7 41 18 AM](https://user-images.githubusercontent.com/52444845/150711215-538b04e3-75f0-4200-9923-23eaf9f4085a.jpeg)

Menu items create the scroll effect
A better idea would be to have a hamburger menu option.

**Comment by deluan** [comment]
Thanks for the suggestion, but I'm not 100% sure I agree. Either way, this is basically a documentation site, and once you go to the "Documentation" section, there is a "hamburger" menu for the docs table of content. Having two hamburger menus would be confusing. 

This site is based on Docsy.dev Hugo template, and I don't think we should deviate that much from it, as it will be harder to upgrade it if/when we want to.

**Comment by tariqrasheed172001** [comment]
I think it would not be confusing 
as we can add navBar hamburger

**Comment by prsndp** [comment]
@deluan I would like to work on this issue. Thanks :)

**Comment by deluan** [comment]
Closing this, as per my previous comment, I don't want to deviate too much from Docsy defaults
